sudo: false
language: node_js
cache:
  directories:
    - node_modules
addons:
    code_climate:
        repo_token: $CODECLIMATE_REPO_TOKEN
matrix:
  fast_finish: true
  include:
    - node_js: "8"
      env: OPENPGP_NODE_JS='8' OPENPGPJSTEST='unit'
    - node_js: "9"
      env: OPENPGP_NODE_JS='9' OPENPGPJSTEST='unit'
    - node_js: "8"
      env: BROWSER='Firefox 34' OPENPGPJSTEST='end2end-0' ALLOW_FAILURE=1
    - node_js: "8"
      env: BROWSER='Firefox 54' OPENPGPJSTEST='end2end-1' ALLOW_FAILURE=1
    - node_js: "8"
      env: BROWSER='Chrome 41' OPENPGPJSTEST='end2end-2' ALLOW_FAILURE=1
    - node_js: "8"
      env: BROWSER='Chrome 59' OPENPGPJSTEST='end2end-3' ALLOW_FAILURE=1
    - node_js: "8"
      env: BROWSER='Safari 8' OPENPGPJSTEST='end2end-4' ALLOW_FAILURE=1
    - node_js: "8"
      env: BROWSER='Safari 10' OPENPGPJSTEST='end2end-5' ALLOW_FAILURE=1
    - node_js: "8"
      env: BROWSER='Android 6.0' OPENPGPJSTEST='end2end-6' ALLOW_FAILURE=1
    - node_js: "8"
      env: BROWSER='iOS 9.3' OPENPGPJSTEST='end2end-7' ALLOW_FAILURE=1
    - node_js: "8"
      env: BROWSER='iOS 11.0' OPENPGPJSTEST='end2end-8' ALLOW_FAILURE=1
    - node_js: "8"
      env: BROWSER='Microsoft Edge 15' OPENPGPJSTEST='end2end-9' ALLOW_FAILURE=1
  allow_failures:
    - env: ALLOW_FAILURE=1

before_script:
  - npm install -g grunt-cli codeclimate-test-reporter
script:
  - $TRAVIS_BUILD_DIR/travis.sh
